version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - funlen
    - godox
    - gomoddirectives
    - exhaustruct
    - nlreturn
    - nonamedreturns
    - noinlineerr
    - paralleltest
    - recvcheck
    - testpackage
    - tparallel
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 3
    cyclop:
      max-complexity: 22
    gocyclo:
      min-complexity: 22
    exhaustive:
      default-signifies-exhaustive: true
      default-case-required: true
    lll:
      line-length: 180
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    # local prefixes regroup imports from these packages
    goimports:
      local-prefixes:
        - github.com/go-openapi
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
