// SPDX-FileCopyrightText: Copyright 2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0

// Package assertions runs integration tests against
// [github.com/go-openapi/testify/v2/internal/assertions].
//
// It verifies that assertion functions never panic when called with
// arbitrary (including nil) values generated by property-based testing
// and Go native fuzzing.
//
// # Motivation
//
// Assertion functions handle values of type [any] and make heavy use
// of [reflect]. Malformed or nil inputs must never cause a nil-pointer
// dereference or other panic; instead the assertion should simply
// return true or false (and optionally mark the test as failed).
//
// The implementation depends on [pgregory.net/rapid].
//
// This internal testing functionality is therefore defined as an
// independent module and does not affect the dependencies of
// [github.com/go-openapi/testify/v2].
package assertions
